# Aider Configuration
# Protocol: Agents-MD Pro v7.5

# ============================================
# PASSIVE CONTEXT INJECTION (True Passive!)
# ============================================
# These files are automatically loaded at startup
# This is the most "passive" implementation possible

read:
  - AGENTS.md
  - PROJECT_GOVERNANCE.md
  - PROJECT_STATUS.md
  - context/memory.md
  - AGENTS_INDEX.yaml

# ============================================
# Core Settings
# ============================================

# Encoding
encoding: utf-8

# Git integration
auto-commits: true
dirty-commits: false

# Safety: require confirmation for large changes
auto-lint: true

# ============================================
# Model Settings (User configurable)
# ============================================
# Uncomment your preferred model:
# model: gpt-4o
# model: claude-3-5-sonnet
# model: deepseek-v3
